### ISSUE TITLE
Withdrew code

### ISSUE THREAD

**Issue by ghost** [CoreModding/Group#10]
I have withdrawn all code I have written from the projects Corporeal and Microdensitometer. You do not have permission to use the removed code. I do not want to argue with shoo and I have decided that I am not welcome here at Corresponding, and am therefore leaving unless the mindset of me not being welcome changes. I also wish to request Conservancy’s code to be removed, as that was also 100% my code. I don't really care as much about that though. Also, I don't care if you remove Reallocating. It was so trashed by proficient (not eccentrically because it's bad code, but it's ugly) it's basically not even my code anyway.

Anyhow, I feel rather sad to go but I must due to my not being welcome. If you guys change your minds about me, or at least Shoo (if it's only him), I will gladly re-join and re-add the code. I only got rid of parts of it that were 100% me anyway.

**Comment by ghost** [comment]
LOLL at the uncorrectable. But anyway, bye :(

**Comment by emwebb** [comment]
If you addressed this issue with the rest of the team early we may have managed to sort out some kind of agreement.

**Comment by ShooShoSha** [comment]
@zeuslightning125 if your code is licensed as open source, we are allowed to use that code so long as we do not violate the license.

**Comment by ShooShoSha** [comment]
Reverted his commits with 9e1156e0824fe55e2837925a320ad2a5a7f9441c and 7d920f41020efa4f69d9c22347e9a6ca0060d8a4

**Comment by ghost** [comment]
I actually have proved that I legally can withdraw it (well, could if given
more time), but I ended up letting shoo leave it anyway.

**Comment by ghost** [comment]
And no, don't bother arguing with me, I have 0 intention of responding to
this again. It's over anyway, and you keep the code.
