### ISSUE TITLE
Conversations on TS Need to be Documented

### ISSUE THREAD

**Issue by ShooShoSha** [CoreModding/Group#3]
When you have discussions on TeamSpeak, any advancements you make needs to be documented for review.

**Comment by ghost** [comment]
I already do this.

**Comment by InternetAthiest** [comment]
Well just make a bot for that

**Comment by ShooShoSha** [comment]
Where do you store them?

**Comment by ghost** [comment]
Notepad, or on the group repo

**Comment by ShooShoSha** [comment]
@kebbanalex A voice transcribing bot would be neat.
