### ISSUE TITLE
Formatting File

### ISSUE THREAD

**Issue by ShooShoSha** [CoreModding/Group#5]
Need to have a file for formatting. In eclipse, a formatting XML may be exported. We will need these files for the IDEs the team uses.

Please list the IDEs you use here so we may prioritize which formatting files to create and export.

_This will be the last step in formatting conventions_

**Comment by ShooShoSha** [comment]
I use eclipse

**Comment by InternetAthiest** [comment]
Well this kinda irritates me https://github.com/CoreModding/Group/blob/master/Conventions/Thoughts.txt

I think that you ShooShoSha, Me, Mushroom and Nerdy_Nathan should have a talk about formatting rules

**Comment by NrdyN8** [comment]
Well, that isn't up to you nor Mushroom. I agree with some items in there, but it is up to Shoo to decide what conventions he wants in the group.

**Comment by ShooShoSha** [comment]
If we have the time, we should have a line-by-line discussion of those, the ones mentioned from Sun Microsystems http://www.oracle.com/technetwork/java/codeconventions-150003.pdf, and other specific issues.

Anyone care to set a meeting?

**Comment by ShooShoSha** [comment]
@NrdyN8 I want to adapt members' styles to enterprise conventions. Not say this is it, deal with it. Unless you want to enforce that?

**Comment by NrdyN8** [comment]
Alright, how about Saturday at 9 MDST, 11 EDT. I am not sure what you mean.

**Comment by eikap** [comment]
I guess I could participate, also @NrdyN8 could you post the rules to the Group repo?

**Comment by NrdyN8** [comment]
I will in a little.

**Comment by eikap** [comment]
Okay

**Comment by ghost** [comment]
I made an "official one" but the export file always is empty.

**Comment by ShooShoSha** [comment]
We will not enforce formatting at this time. If it becomes an issue again, we will open a new issue (and reference this one).
