### ISSUE TITLE
Git Permissions

### ISSUE THREAD

**Issue by ShooShoSha** [CoreModding/Group#6]
I have looked at all the repositories and any issues associated with them. I examined the teams and the repositories they possess. The majority of issues stem from everybody having write access to every repository.There needs to be some control of members pushing any change to the repositories.

**Comment by ShooShoSha** [comment]
All _organization_ members are encouraged to contribute to whichever repository they would like to get involved. However, it should be up to the team(s) collaborating on that repository to discriminate which changes are made. Thus changes to repositories from non-explicit team members must be made through pull requests.

If you want to avoid managing many pull requests, you may elect to add a member with write privileges if you:
- Communicate well
- Trust their judgement
- Won't despise one another after a mistake
- Other circumstances should be discussed prior to adding team members

**Comment by eikap** [comment]
Well, in my opinion, we should not work on separate mods, but focus on one of them and get it done, and I think that it's good that we can help each other, so we dont need to use pull requests each time we do anything, because we're a team, and we should work as a team.
As such I dissagree with @ShooShoSha.

**Comment by NrdyN8** [comment]
The way I have it setup is the way is should be. Only the groups with the same name as the mods as well as the Admins can write to it. There is a project ead on each mod and only with expressed written permission from either the mod lead or an admin can someone then be added to the group and be allowed to work on it.

**Comment by ShooShoSha** [comment]
If priority demands it, we can task members to write code for a specific project if it needs to be completed or repaired quickly. But all those pushes need to have a review process by members of the team of that project; they have the most knowledge of what the client wants and what the mod should do.

Think of team members as a code review panel. They can push anything they want to the repository because they have exclusivity over the project. When someone outside the team makes contributions, you want to make sure it doesn't break all the work you've made. Thus they make pull requests.

The pull requests are only to control what is put into the remote repository. If you want a member to avoid making pull requests, they can be added to the team and be granted explicit write permissions.

**Comment by NrdyN8** [comment]
Wait, I thought that is what I said. Maybe it wasn't, I don't know. But yes, that is the way I want it and the way it should be.

**Comment by ShooShoSha** [comment]
@NrdyN8 I wanted to elaborate the thought process I had and what you wrote.

**Comment by eikap** [comment]
BTW have ShooShoSha replaced zeus as an admin? Tf?

**Comment by NrdyN8** [comment]
Yes.

**Comment by NrdyN8** [comment]
Zeus has broken a few rules again. Although Zeus can still return after I see that he has changed.

**Comment by eikap** [comment]
And why is ShooShoSha an admin? Just curious

**Comment by eikap** [comment]
And what rules? Do we have any? :/

**Comment by NrdyN8** [comment]
Yes, I forgot who was on the IRC when I posted them. They will be up saturday when I can get back on the account.

**Comment by NrdyN8** [comment]
We have a list of rules, it is just that Zeus has been asked before to stop and he didn't. I would have let it go if it was a first offense being that the rules aren't up on the forum yet.

**Comment by ShooShoSha** [comment]
@MushroomLT If you have suggestions to prevent code push abuse, I would be glad to listen to them.

**Comment by eikap** [comment]
What "Abuse" do we have now?

**Comment by eikap** [comment]
I cant suggest how to solve a problem if I dont see the problem itself
And, @NrdyN8 why is ShooShoSha an admin?

**Comment by NrdyN8** [comment]
He has the most experience.

**Comment by eikap** [comment]
In coding>?

**Comment by NrdyN8** [comment]
Yep.

**Comment by eikap** [comment]
Ok

**Comment by ShooShoSha** [comment]
@MushroomLT The abuse is the lack of discussion when make changes to the remote repos. One issue: CoreModding/CORE-API#2 when the developing version was switched without notice. Also this commit: https://github.com/CoreModding/Craftable-Enchantments/commit/113da653983f8a30fadcac6a4bd84037ab2ffac2 was made without discussion and the message unprofessional.

**Comment by ghost** [comment]
Who does nrdy? Also, that commit doesnt exist.

**Comment by NrdyN8** [comment]
ShooShoSha

**Comment by eikap** [comment]
@zeuslightning125 click on Crafttable Enchantments not on the commit id.

**Comment by ghost** [comment]
I think it's flowing smoothly now. Let me know if you want me to re-open this.
