### ISSUE TITLE
Creating CORE games

### ISSUE THREAD

**Issue by NrdyN8** [CoreModding/Group#7]
I was wondering if anyone would object to me starting CORE games?

**Comment by eikap** [comment]
Like a game making group?

**Comment by NrdyN8** [comment]
Yes.

**Comment by eikap** [comment]
Would it be a separate group, or just the same group, but making games too? Cause I would like to participate.

**Comment by NrdyN8** [comment]
Sort of both. It is a seperate group, but everyone here is encouraged to join.

**Comment by eikap** [comment]
I have some experience with Unreal Engine, but i'm not much of an modeler/texturer

**Comment by InternetAthiest** [comment]
Well we started as a mod developing group and now game developing group O.o

**Comment by NrdyN8** [comment]
Neither am I. http://www.nerdynathan.com I have my first game I ever made up there.

**Comment by NrdyN8** [comment]
And yes @kebbanalex that is what I was planning on all along.

**Comment by NrdyN8** [comment]
Why stop at mods when there is so much potential.

**Comment by ghost** [comment]
I was interested in making some games and had some awesome ideas floating
around that I wanted to present later, bur quite frankly knowing I can be
kicked out of the group without warning unnerved me. All of them could have
been profitable, so I will try to do it in a group that I can trust to stay
in or by myself.

I can't really do much for a group if I know I may loose all of my work and
have them take all of the credit at any time.

I really dont trust you guys enough anymore to do anything. Can we come to
some sort of agreement related to this so I can feel assured about my work?

**Comment by ghost** [comment]
Anyhow, I'm up for it whenever you all are interested.

**Comment by ShooShoSha** [comment]
This question was answered.
