### ISSUE TITLE
Branch naming convention

### ISSUE THREAD

**Issue by ShooShoSha** [CoreModding/Group#9]
This was brought up in a conversation. The current naming convention for our branches are based on the Minecraft version supported by Forge.

For example, Forge version 10.12.1.1117 supports Minecraft version 1.7.2 so we have a branch called 1.7.2 for that code. Even though Forge will update, if it doesn't move to the next Minecraft version the branch remains.

As for the version of the mod itself, this is handled by using tags. So if you have a build (be it alpha, beta, or release) you tag the repo with the version number (e.g. 0.1.42/beta). The versioning semantics is at the mod author's discretion.

In essence, I would like a discussion about what you want as a branching/tagging scheme. I am doing a bit more research about tags and how other repos handle branching (https://github.com/scala/scala is a starting place).

**Comment by RoboRave** [comment]
sounds like a good idea

**Comment by ghost** [comment]
So 1.7.2/0.0.1/Dev? Sounds good.

**Comment by ShooShoSha** [comment]
This is a continuation of issue #4
